// <auto-generated />
using System;
using MedicLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicLab.Data.Migrations
{
    [DbContext(typeof(MedicLabDbContext))]
    partial class MedicLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicLab.Data.Entities.AppointmentDetail", b =>
                {
                    b.Property<int>("AppointmentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentDetailId"));

                    b.Property<int>("AppointmentOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicalStudyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("AppointmentDetailId");

                    b.HasIndex("AppointmentOrderId");

                    b.HasIndex("ClinicalStudyId");

                    b.ToTable("AppointmentDetails");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.AppointmentOrder", b =>
                {
                    b.Property<int>("AppointmentOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentOrderId"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AppointmentOrderId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("AppointmentOrders");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("ClinicalStudyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Day")
                        .HasColumnType("date");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("ClinicalStudyId", "Day")
                        .IsUnique();

                    b.ToTable("Availability", t =>
                        {
                            t.HasCheckConstraint("CK_ClinicalStudies_AvailableDays", "[Day] >= CONVERT(date, GETDATE())");
                        });

                    b.HasData(
                        new
                        {
                            AvailabilityId = 1,
                            ClinicalStudyId = 2,
                            Day = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 10,
                            Slots = 20
                        },
                        new
                        {
                            AvailabilityId = 2,
                            ClinicalStudyId = 3,
                            Day = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 5,
                            Slots = 3
                        },
                        new
                        {
                            AvailabilityId = 3,
                            ClinicalStudyId = 1,
                            Day = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 20,
                            Slots = 15
                        },
                        new
                        {
                            AvailabilityId = 4,
                            ClinicalStudyId = 3,
                            Day = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 5,
                            Slots = 4
                        });
                });

            modelBuilder.Entity("MedicLab.Data.Entities.ClinicalStudy", b =>
                {
                    b.Property<int>("ClinicalStudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicalStudyId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LOINC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ClinicalStudyId");

                    b.HasIndex(new[] { "LOINC" }, "UQ_ClinicalStudies")
                        .IsUnique();

                    b.ToTable("ClinicalStudies");

                    b.HasData(
                        new
                        {
                            ClinicalStudyId = 1,
                            Description = "It measures the amount of glucose mass per unit volume present in a blood sample.",
                            LOINC = "2345-7",
                            StudyName = "Glucose [Mass/volume] in Blood"
                        },
                        new
                        {
                            ClinicalStudyId = 2,
                            Description = "It specifically identifies the glucose concentration, but changes the system (urine) and timing (24-hour collection).",
                            LOINC = "2546-9",
                            StudyName = "Glucose [Mass/volume] in 24 hour Urine"
                        },
                        new
                        {
                            ClinicalStudyId = 3,
                            Description = "Indicates the presence of the SARS-CoV-2 virus (qualitative) using a nucleic acid amplification test (such as PCR) in a respiratory specimen.",
                            LOINC = "94500-6",
                            StudyName = "SARS-CoV-2 (COVID-19) RNA [Presence] in Respiratory specimen by NAA with probe detection"
                        });
                });

            modelBuilder.Entity("MedicLab.Data.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicalLicense")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            FirstName = "Mario",
                            LastName = "Ruiz",
                            MedicalLicense = "AR76097"
                        },
                        new
                        {
                            DoctorId = 2,
                            FirstName = "Luisa",
                            LastName = "Romero",
                            MedicalLicense = "TR42850"
                        });
                });

            modelBuilder.Entity("MedicLab.Data.Entities.EventLog", b =>
                {
                    b.Property<int>("EventLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventLogId"));

                    b.Property<int?>("AppointmentOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EventLogId");

                    b.HasIndex("AppointmentOrderId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.FulfillmentEvent", b =>
                {
                    b.Property<int>("FulfillmentEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FulfillmentEventId"));

                    b.Property<int>("AppointmentOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FulfilledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FulfillmentEventId");

                    b.HasIndex("AppointmentOrderId")
                        .IsUnique();

                    b.ToTable("FulfillmentEvents");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CURP")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PatientId");

                    b.HasIndex(new[] { "CURP" }, "UQ_Patient_Curp")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ_Patient_Email")
                        .IsUnique();

                    b.ToTable("Patients", t =>
                        {
                            t.HasCheckConstraint("CK_Patient_Birthdate", "[BirthDate] <= CONVERT(date, GETDATE())");
                        });

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            BirthDate = new DateTime(2003, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CURP = "PEAS030328HJCRLMA4",
                            Email = "Samuelpalfaro@gmail.com",
                            FirstName = "Samuel",
                            LastName = "Pérez"
                        },
                        new
                        {
                            PatientId = 2,
                            BirthDate = new DateTime(1956, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CURP = "SABC5560626MDFLRN0",
                            Email = "Concepcion@mail.com",
                            FirstName = "Concepción",
                            LastName = "Salgado"
                        });
                });

            modelBuilder.Entity("MedicLab.Data.Entities.AppointmentDetail", b =>
                {
                    b.HasOne("MedicLab.Data.Entities.AppointmentOrder", "AppointmentOrder")
                        .WithMany("Details")
                        .HasForeignKey("AppointmentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicLab.Data.Entities.ClinicalStudy", "ClinicalStudy")
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("ClinicalStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentOrder");

                    b.Navigation("ClinicalStudy");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.AppointmentOrder", b =>
                {
                    b.HasOne("MedicLab.Data.Entities.Doctor", "Doctor")
                        .WithMany("AppointmentOrders")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicLab.Data.Entities.Patient", "Patient")
                        .WithMany("AppointmentOrders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.Availability", b =>
                {
                    b.HasOne("MedicLab.Data.Entities.ClinicalStudy", "ClinicalStudy")
                        .WithMany("Availability")
                        .HasForeignKey("ClinicalStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicalStudy");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.EventLog", b =>
                {
                    b.HasOne("MedicLab.Data.Entities.AppointmentOrder", "AppointmentOrder")
                        .WithMany("EventLog")
                        .HasForeignKey("AppointmentOrderId");

                    b.Navigation("AppointmentOrder");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.FulfillmentEvent", b =>
                {
                    b.HasOne("MedicLab.Data.Entities.AppointmentOrder", "AppointmentOrder")
                        .WithOne("FulfillmentEvent")
                        .HasForeignKey("MedicLab.Data.Entities.FulfillmentEvent", "AppointmentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentOrder");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.AppointmentOrder", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("EventLog");

                    b.Navigation("FulfillmentEvent");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.ClinicalStudy", b =>
                {
                    b.Navigation("AppointmentDetails");

                    b.Navigation("Availability");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.Doctor", b =>
                {
                    b.Navigation("AppointmentOrders");
                });

            modelBuilder.Entity("MedicLab.Data.Entities.Patient", b =>
                {
                    b.Navigation("AppointmentOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
